import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "src/context/AuthContext"; // 👈 import context

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Diagnosis Of Bone Tumor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider> {/* 👈 wrap inside AuthProvider */}
      </body>
    </html>
  );
}







